import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, Loader2, Printer } from "lucide-react";
import { useLocation, useRoute } from "wouter";

const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export default function InvoicePrint() {
  const [, params] = useRoute("/invoices/:id/print");
  const [, setLocation] = useLocation();
  const invoice = trpc.accounting.invoices.get.useQuery({ id: Number(params?.id) }, { enabled: Boolean(params?.id) });
  if (invoice.isLoading) return <div className="grid min-h-screen place-items-center"><Loader2 className="animate-spin" /></div>;
  if (!invoice.data) return <div className="grid min-h-screen place-items-center"><p>Invoice not found.</p></div>;
  const item = invoice.data;
  return <div className="min-h-screen bg-zinc-200 p-4 print:bg-white print:p-0"><div className="print:hidden mx-auto mb-4 flex max-w-3xl justify-between"><Button onClick={() => setLocation("/invoices")} variant="outline" className="rounded-none border-black/30"><ArrowLeft className="mr-2 h-4 w-4" />Back</Button><Button onClick={() => window.print()} className="rounded-none bg-black text-white"><Printer className="mr-2 h-4 w-4" />Print / Save PDF</Button></div><article className="invoice-sheet mx-auto max-w-3xl bg-white p-8 shadow-xl sm:p-12 print:max-w-none print:shadow-none"><header className="flex items-start justify-between border-b-4 border-black pb-8"><div><p className="ledger-kicker">LEDGERWISE / INVOICE</p><h1 className="mt-3 text-5xl font-black uppercase tracking-[-.08em]">Invoice</h1></div><div className="text-right"><p className="text-lg font-black">#{item.number}</p><p className="mt-1 text-sm text-black/55">Issued {new Date(item.issueAt).toLocaleDateString()}</p><p className="text-sm text-black/55">Due {new Date(item.dueAt).toLocaleDateString()}</p></div></header><section className="grid gap-8 py-9 sm:grid-cols-2"><div><p className="ledger-kicker">BILL TO</p><p className="mt-3 text-xl font-black">{item.customer?.name ?? "Customer"}</p><p className="mt-1 whitespace-pre-line text-sm text-black/60">{item.customer?.email}{item.customer?.address ? `\n${item.customer.address}` : ""}</p></div><div className="sm:text-right"><p className="ledger-kicker">PAYMENT STATUS</p><p className="mt-3 inline-block bg-black px-3 py-1 text-xs font-bold uppercase tracking-widest text-white">{item.displayStatus}</p></div></section><table className="w-full border-collapse text-left"><thead className="border-y-2 border-black text-[10px] uppercase tracking-[.14em]"><tr><th className="py-3">Description</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Rate</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{item.items.map(line => <tr className="border-b border-black/15" key={line.id}><td className="py-4 font-medium">{line.description}</td><td className="py-4 text-right">{line.quantity}</td><td className="py-4 text-right">{money(line.unitAmountCents)}</td><td className="py-4 text-right font-bold">{money(line.lineTotalCents)}</td></tr>)}</tbody></table><div className="ml-auto mt-8 max-w-xs"><div className="flex justify-between border-b border-black/15 py-3 text-sm"><span>Subtotal</span><span>{money(item.subtotalCents)}</span></div><div className="flex justify-between border-b border-black/15 py-3 text-sm"><span>Tax</span><span>{money(item.taxCents)}</span></div><div className="flex justify-between py-4 text-2xl font-black uppercase tracking-[-.055em]"><span>Total</span><span>{money(item.totalCents)}</span></div></div>{item.notes && <footer className="mt-12 border-t border-black/20 pt-5"><p className="ledger-kicker">NOTES</p><p className="mt-2 text-sm leading-6 text-black/65">{item.notes}</p></footer>}</article></div>;
}
