import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Loader2, Printer, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { useRoute } from "wouter";

const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export default function PublicInvoice() {
  const [, params] = useRoute("/pay/:token");
  const invoice = trpc.accounting.invoices.getPublic.useQuery({ publicToken: params?.token ?? "invalid" }, { enabled: Boolean(params?.token) });
  const checkout = trpc.payments.createPublicInvoiceCheckout.useMutation({ onSuccess: ({ url }) => window.location.assign(url), onError: error => toast.error(error.message) });
  if (invoice.isLoading) return <div className="grid min-h-screen place-items-center bg-zinc-100"><Loader2 className="animate-spin" /></div>;
  if (!invoice.data) return <div className="grid min-h-screen place-items-center bg-zinc-100 p-6 text-center"><div><p className="ledger-kicker">LEDGERWISE</p><h1 className="mt-3 text-4xl font-black uppercase tracking-[-.06em]">Invoice unavailable</h1><p className="mt-3 text-sm text-black/55">This payment link may be invalid, expired, or not yet sent.</p></div></div>;
  const item = invoice.data;
  return <main className="min-h-screen bg-zinc-200 p-4 sm:p-8 print:bg-white print:p-0"><article className="invoice-sheet mx-auto max-w-3xl bg-white p-7 shadow-xl sm:p-12 print:max-w-none print:shadow-none"><header className="flex items-start justify-between border-b-4 border-black pb-8"><div><p className="ledger-kicker">LEDGERWISE / PAYMENT REQUEST</p><h1 className="mt-3 text-5xl font-black uppercase tracking-[-.08em]">Invoice</h1></div><div className="text-right"><p className="text-lg font-black">#{item.number}</p><p className="mt-1 text-sm text-black/55">Due {new Date(item.dueAt).toLocaleDateString()}</p></div></header><section className="grid gap-8 py-9 sm:grid-cols-2"><div><p className="ledger-kicker">BILL TO</p><p className="mt-3 text-xl font-black">{item.customer?.name ?? "Customer"}</p></div><div className="sm:text-right"><p className="ledger-kicker">STATUS</p><p className="mt-3 inline-block bg-black px-3 py-1 text-xs font-bold uppercase tracking-widest text-white">{item.displayStatus}</p></div></section><table className="w-full border-collapse text-left"><thead className="border-y-2 border-black text-[10px] uppercase tracking-[.14em]"><tr><th className="py-3">Description</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{item.items.map(line => <tr className="border-b border-black/15" key={line.id}><td className="py-4 font-medium">{line.description}</td><td className="py-4 text-right">{line.quantity}</td><td className="py-4 text-right font-bold">{money(line.lineTotalCents)}</td></tr>)}</tbody></table><div className="ml-auto mt-8 max-w-xs"><div className="flex justify-between border-b border-black/15 py-3 text-sm"><span>Subtotal</span><span>{money(item.subtotalCents)}</span></div><div className="flex justify-between border-b border-black/15 py-3 text-sm"><span>Tax</span><span>{money(item.taxCents)}</span></div><div className="flex justify-between py-4 text-2xl font-black uppercase tracking-[-.055em]"><span>Total</span><span>{money(item.totalCents)}</span></div></div>{item.status !== "paid" && <div className="mt-10 flex flex-wrap items-center gap-3 print:hidden"><Button disabled={checkout.isPending} onClick={() => checkout.mutate({ publicToken: item.publicToken, origin: window.location.origin })} className="rounded-none bg-black px-6 font-bold uppercase tracking-wider text-white">{checkout.isPending ? "Redirecting…" : `Pay ${money(item.totalCents)}`}</Button><Button onClick={() => window.print()} variant="outline" className="rounded-none border-black/30"><Printer className="mr-2 h-4 w-4" />Print</Button><span className="flex items-center gap-1 text-xs text-black/50"><ShieldCheck className="h-4 w-4" />Secure checkout by Stripe</span></div>}{item.notes && <footer className="mt-12 border-t border-black/20 pt-5"><p className="ledger-kicker">NOTES</p><p className="mt-2 text-sm leading-6 text-black/65">{item.notes}</p></footer>}</article></main>;
}
